const PASSWORD_RESET_EMAIL_REQUEST = 'PASSWORD_RESET_EMAIL_REQUEST';
const PASSWORD_RESET_EMAIL_SUCCESS = 'PASSWORD_RESET_EMAIL_SUCCESS';
const PASSWORD_RESET_EMAIL_FAIL = 'PASSWORD_RESET_EMAIL_FAIL';

export default {
    PASSWORD_RESET_EMAIL_REQUEST,
    PASSWORD_RESET_EMAIL_SUCCESS,
    PASSWORD_RESET_EMAIL_FAIL
}